package com.bohouse.pacemeter.core.model;

import java.util.Map;

public final class ActionNameLibrary {

    private static final Map<Integer, String> ACTION_NAMES = Map.ofEntries(
            Map.entry(0x8C0, "spinning edge"),
            Map.entry(0x8C2, "gust slash"),
            Map.entry(0x8C6, "assassinate"),
            Map.entry(0x8C7, "throwing dagger"),
            Map.entry(0x8C8, "mug"),
            Map.entry(0x8CE, "death blossom"),
            Map.entry(0x8CF, "aeolian edge"),
            Map.entry(0x8D2, "trick attack"),
            Map.entry(0x8D9, "fuma shuriken"),
            Map.entry(0x8DA, "katon"),
            Map.entry(0x8DB, "raiton"),
            Map.entry(0x8DC, "hyoton"),
            Map.entry(0x8DD, "huton"),
            Map.entry(0x8DF, "suiton"),
            Map.entry(0xDEB, "armor crush"),
            Map.entry(0xDEE, "dream within a dream"),
            Map.entry(0x1CE9, "hellfrog medium"),
            Map.entry(0x1CEA, "bhavacakra"),
            Map.entry(0x4068, "hakke mijinsatsu"),
            Map.entry(0x406B, "goka mekkyaku"),
            Map.entry(0x406C, "hyosho ranryu"),
            Map.entry(0x64AE, "phantom kamaitachi"),
            Map.entry(0x64B0, "hollow nozuchi"),
            Map.entry(0x64B1, "forked raiju"),
            Map.entry(0x64B2, "fleeting raiju"),
            Map.entry(0x905D, "dokumori"),
            Map.entry(0x905E, "kunai's bane"),
            Map.entry(0x905F, "deathfrog medium"),
            Map.entry(0x9060, "zesho meppo"),
            Map.entry(0x9061, "tenri jindo"),
            Map.entry(0x5EDB, "dosis"),
            Map.entry(0x5EDC, "diagnosis"),
            Map.entry(0x5EDE, "prognosis"),
            Map.entry(0x5EE1, "phlegma"),
            Map.entry(0x5EE3, "eukrasian diagnosis"),
            Map.entry(0x5EE4, "eukrasian prognosis"),
            Map.entry(0x5EE5, "eukrasian dosis"),
            Map.entry(0x5EE8, "druochole"),
            Map.entry(0x5EE9, "dyskrasia"),
            Map.entry(0x5EEB, "ixochole"),
            Map.entry(0x5EED, "pepsis"),
            Map.entry(0x5EEF, "taurochole"),
            Map.entry(0x5EF0, "toxikon"),
            Map.entry(0x5EF2, "dosis ii"),
            Map.entry(0x5EF3, "phlegma ii"),
            Map.entry(0x53F4, "eukrasian dosis ii"),
            Map.entry(0x5EF6, "holos"),
            Map.entry(0x5EF8, "dosis iii"),
            Map.entry(0x5EF9, "phlegma iii"),
            Map.entry(0x5EFA, "eukrasian dosis iii"),
            Map.entry(0x5EFB, "dyskrasia ii"),
            Map.entry(0x5EFC, "toxikon ii"),
            Map.entry(0x5EFE, "pneuma attack"),
            Map.entry(0x6B84, "pneuma heal"),
            Map.entry(0x90A8, "eukrasian dyskrasia"),
            Map.entry(0x90A9, "psyche"),
            Map.entry(0x90AA, "eukrasian prognosis ii"),
            Map.entry(0x004B, "true thrust"),
            Map.entry(0x004E, "vorpal thrust"),
            Map.entry(0x0054, "full thrust"),
            Map.entry(0x0056, "doom spike"),
            Map.entry(0x0057, "disembowel"),
            Map.entry(0x0058, "chaos thrust"),
            Map.entry(0x005A, "piercing talon"),
            Map.entry(0x005C, "jump"),
            Map.entry(0x0060, "dragonfire dive"),
            Map.entry(0x0DE2, "fang and claw"),
            Map.entry(0x0DE3, "geirskogul"),
            Map.entry(0x0DE4, "wheeling thrust"),
            Map.entry(0x1CE5, "sonic thrust"),
            Map.entry(0x1CE7, "mirage dive"),
            Map.entry(0x1CE8, "nastrond"),
            Map.entry(0x405D, "coerthan torment"),
            Map.entry(0x405E, "high jump"),
            Map.entry(0x405F, "raiden thrust"),
            Map.entry(0x4060, "stardiver"),
            Map.entry(0x64AA, "draconian fury"),
            Map.entry(0x64AB, "heavens' thrust"),
            Map.entry(0x64AC, "chaotic spring"),
            Map.entry(0x64AD, "wyrmwind thrust"),
            Map.entry(0x9058, "drakesbane"),
            Map.entry(0x9059, "rise of the dragon"),
            Map.entry(0x905A, "lance barrage"),
            Map.entry(0x905B, "spiral blow"),
            Map.entry(0x905C, "starcross"),
            Map.entry(0x00A7, "energy drain"),
            Map.entry(0x00B9, "adloquium"),
            Map.entry(0x00BA, "succor"),
            Map.entry(0x00BD, "lustrate"),
            Map.entry(0x00BE, "physick"),
            Map.entry(0x0322, "embrace"),
            Map.entry(0x0DFF, "indomitability"),
            Map.entry(0x0E00, "broil"),
            Map.entry(0x1D0B, "broil ii"),
            Map.entry(0x409B, "art of war"),
            Map.entry(0x409D, "broil iii"),
            Map.entry(0x409F, "fey blessing"),
            Map.entry(0x40A0, "fey blessing"),
            Map.entry(0x40A2, "consolation"),
            Map.entry(0x40A3, "consolation"),
            Map.entry(0x40A4, "seraphic veil"),
            Map.entry(0x45CD, "ruin-scholar"),
            Map.entry(0x45CE, "ruin ii"),
            Map.entry(0x6509, "broil iv"),
            Map.entry(0x650A, "art of war ii"),
            Map.entry(0x650B, "protraction"),
            Map.entry(0x9095, "concitation"),
            Map.entry(0x9097, "manifestation"),
            Map.entry(0x9098, "accession")
    );

    private static final Map<Integer, String> ACTION_DISPLAY_NAMES = Map.ofEntries(
            Map.entry(0x8C0, "스피닝 엣지"),
            Map.entry(0x8C2, "거스트 슬래시"),
            Map.entry(0x8C6, "어새시네이트"),
            Map.entry(0x8C7, "투척 단검"),
            Map.entry(0x8C8, "훔쳐보기"),
            Map.entry(0x8CE, "데스 블로섬"),
            Map.entry(0x8CF, "에올리안 엣지"),
            Map.entry(0x8D2, "트릭 어택"),
            Map.entry(0x8D9, "풍마수리검"),
            Map.entry(0x8DA, "화둔"),
            Map.entry(0x8DB, "뇌둔"),
            Map.entry(0x8DC, "빙둔"),
            Map.entry(0x8DD, "풍둔"),
            Map.entry(0x8DF, "수둔"),
            Map.entry(0xDEB, "갑쇄 베기"),
            Map.entry(0xDEE, "몽환삼단"),
            Map.entry(0x1CE9, "생사여탈"),
            Map.entry(0x1CEA, "나찰충격"),
            Map.entry(0x4068, "팔괘무인살"),
            Map.entry(0x406B, "겁화멸각"),
            Map.entry(0x406C, "효쇼 란류"),
            Map.entry(0x64AE, "환영 가마이타치"),
            Map.entry(0x64B0, "허영 노즈치"),
            Map.entry(0x64B1, "갈래 뇌수"),
            Map.entry(0x64B2, "성긴 뇌수"),
            Map.entry(0x905D, "독무리"),
            Map.entry(0x905E, "쿠나이즈 베인"),
            Map.entry(0x905F, "데스프로그 미디엄"),
            Map.entry(0x9060, "제쇼 멧포"),
            Map.entry(0x9061, "천리지도"),
            Map.entry(0x5EDB, "도시스"),
            Map.entry(0x5EDC, "진단"),
            Map.entry(0x5EDE, "예후"),
            Map.entry(0x5EE1, "플레그마"),
            Map.entry(0x5EE3, "유크라시아 진단"),
            Map.entry(0x5EE4, "유크라시아 예후"),
            Map.entry(0x5EE5, "유크라시아 도시스"),
            Map.entry(0x5EE8, "드루오콜"),
            Map.entry(0x5EE9, "디스크라시아"),
            Map.entry(0x5EEB, "익소콜"),
            Map.entry(0x5EED, "펩시스"),
            Map.entry(0x5EEF, "타우로콜"),
            Map.entry(0x5EF0, "톡시콘"),
            Map.entry(0x5EF2, "도시스 II"),
            Map.entry(0x5EF3, "플레그마 II"),
            Map.entry(0x53F4, "유크라시아 도시스 II"),
            Map.entry(0x5EF6, "홀로스"),
            Map.entry(0x5EF8, "도시스 III"),
            Map.entry(0x5EF9, "플레그마 III"),
            Map.entry(0x5EFA, "유크라시아 도시스 III"),
            Map.entry(0x5EFB, "디스크라시아 II"),
            Map.entry(0x5EFC, "톡시콘 II"),
            Map.entry(0x5EFE, "프뉴마 공격"),
            Map.entry(0x6B84, "프뉴마 회복"),
            Map.entry(0x90A8, "유크라시아 디스크라시아"),
            Map.entry(0x90A9, "프시케"),
            Map.entry(0x90AA, "유크라시아 예후 II"),
            Map.entry(0x004B, "정권 지르기"),
            Map.entry(0x004E, "몸통 가르기"),
            Map.entry(0x0054, "올려 찌르기"),
            Map.entry(0x0056, "둠 스파이크"),
            Map.entry(0x0057, "이음새 찌르기"),
            Map.entry(0x0058, "카오스 쓰러스트"),
            Map.entry(0x005A, "관통탄"),
            Map.entry(0x005C, "점프"),
            Map.entry(0x0060, "용염쇄"),
            Map.entry(0x0DE2, "송곳니와 발톱"),
            Map.entry(0x0DE3, "게이르스코굴"),
            Map.entry(0x0DE4, "몸통 회전 찌르기"),
            Map.entry(0x1CE5, "소닉 쓰러스트"),
            Map.entry(0x1CE7, "미라지 다이브"),
            Map.entry(0x1CE8, "나스트론드"),
            Map.entry(0x405D, "코어선 토멘트"),
            Map.entry(0x405E, "하이 점프"),
            Map.entry(0x405F, "라이덴 스러스트"),
            Map.entry(0x4060, "스타다이버"),
            Map.entry(0x64AA, "드라코니안 퓨리"),
            Map.entry(0x64AB, "헤븐스 스러스트"),
            Map.entry(0x64AC, "카오틱 스프링"),
            Map.entry(0x64AD, "웜윈드 스러스트"),
            Map.entry(0x9058, "드레이크베인"),
            Map.entry(0x9059, "라이즈 오브 더 드래곤"),
            Map.entry(0x905A, "랜스 배러지"),
            Map.entry(0x905B, "스파이럴 블로우"),
            Map.entry(0x905C, "스타크로스"),
            Map.entry(0x00A7, "에너지 드레인"),
            Map.entry(0x00B9, "고무격려책"),
            Map.entry(0x00BA, "사기고양책"),
            Map.entry(0x00BD, "생명활성술"),
            Map.entry(0x00BE, "물리 치료"),
            Map.entry(0x0322, "포옹"),
            Map.entry(0x0DFF, "불굴의 의지"),
            Map.entry(0x0E00, "브로일"),
            Map.entry(0x1D0B, "브로일 II"),
            Map.entry(0x409B, "아트 오브 워"),
            Map.entry(0x409D, "브로일 III"),
            Map.entry(0x409F, "페이 블레싱"),
            Map.entry(0x40A0, "페이 블레싱"),
            Map.entry(0x40A2, "위안"),
            Map.entry(0x40A3, "위안"),
            Map.entry(0x40A4, "세라픽 베일"),
            Map.entry(0x45CD, "루인"),
            Map.entry(0x45CE, "루인 II"),
            Map.entry(0x6509, "브로일 IV"),
            Map.entry(0x650A, "아트 오브 워 II"),
            Map.entry(0x650B, "전개전술"),
            Map.entry(0x9095, "콘시테이션"),
            Map.entry(0x9097, "매니페스테이션"),
            Map.entry(0x9098, "액세션")
    );

    private ActionNameLibrary() {
    }

    public static String resolve(int actionId) {
        if (actionId <= 0) {
            return "";
        }
        String known = resolveKnown(actionId);
        if (known != null && !known.isBlank()) {
            return known;
        }
        return "0x" + Integer.toHexString(actionId).toUpperCase();
    }

    public static String resolveKnown(int actionId) {
        if (actionId <= 0) {
            return "";
        }
        return ACTION_NAMES.getOrDefault(actionId, "");
    }

    public static String resolveDisplay(int actionId) {
        if (actionId <= 0) {
            return "";
        }
        String display = ACTION_DISPLAY_NAMES.get(actionId);
        if (display != null && !display.isBlank()) {
            return display;
        }
        return resolve(actionId);
    }
}
